# Generated by Django 2.1.7 on 2021-11-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_goods_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
